### PR TITLE
added model 1 SVM

### PR DESCRIPTION
**Pull request by jmsanders55**

### CODE REVIEW

**Comment by jmsanders55** [comment]
Aniket, I'm still having trouble fully running the SVM model with cross-validation. It's been running now for over 4 hours. It starts on Model 1 around line 18. Any suggestions? Thanks!

**Comment by Akesari12** [comment]
I would try to scale the data as follows:

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

I'm running this on my end now to see if it improves your time. I also wasn't sure which notebook is the most recent, I think the one labeled "6"? Otherwise, I'd let it run overnight if you can!

**Comment by jmsanders55** [comment]
> I would try to scale the data as follows:
> 
> from sklearn.preprocessing import StandardScaler
> scaler = StandardScaler()
> X = scaler.fit_transform(X)
> 
> I'm running this on my end now to see if it improves your time. I also wasn't sure which notebook is the most recent, I think the one labeled "6"? Otherwise, I'd let it run overnight if you can!

Thanks, yes it was "6". Also we had that question about running it overnight, will it run if it logs off of the wifi overnight? I'll leave my laptop open and connected to the power cord, but it will eventually go into sleep mode and log off of wifi. Will it continue to run if it's off wifi?

**Comment by Akesari12** [comment]
It'll work when it's not on wifi- less sure about if the computer goes to sleep depending on the sleep settings but it's a worth a shot. If that doesn't work I'll see if there's a better solution!

**Comment by jmsanders55** [comment]
> It'll work when it's not on wifi- less sure about if the computer goes to sleep depending on the sleep settings but it's a worth a shot. If that doesn't work I'll see if there's a better solution!

Thanks!!

**Comment by jmsanders55** [comment]
> > It'll work when it's not on wifi- less sure about if the computer goes to sleep depending on the sleep settings but it's a worth a shot. If that doesn't work I'll see if there's a better solution!
> 
> Thanks!!

It ran over night, yay! Aniket, what's the code to save the output so I don't have to re-run it again? I thought I had it saved but I didn't. Thanks!

Jasmine

**Comment by Akesari12** [comment]
Awesome! This tutorial should be helpful: https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/

The basic idea is that you can save the model as a pickle object and then access it again later. Basically run these lines and sub in your model:

import pickle

# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))

# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))

**Pull request merged**
