### PR TITLE
updated svm plus validation metrics

### PR DESCRIPTION
**Pull request by jmsanders55**
Looks like I can't automatically merge, not sure why though =/

### CODE REVIEW

**Comment by dianacasanova** [comment]
Hey Jasmine,

I'm such a github newbie. Not sure how to do this review/merge with resolving conflicts. Mostly worried about erasing stuff in the latest version. You want to just go ahead and merge it in?  I can also try and do some copy&pasting into a "master" notebook. Let me know what you think.

Thanks!
Diana

**Comment by jmsanders55** [comment]
I'm actually not quite sure either Diana. I just tried to follow the command line instructions linked by github above, and it didn't work. It says my branch is behind so it's not letting me merge. I thought about pulling fresh but then it will delete the svm stuff I've already done and I don't want to run that again :( I think the issue is that it's flagging all the code I interrupted from my former SVM model as a conflict because I have completely different output there now (I think that's the issue). I don't know how to override it though. Vincent, any thoughts here?

**Comment by dianacasanova** [comment]
Thanks for looking into it! Let me try to manually/brute force combine our code. Stay tuned!

-Diana

**Comment by vincent17890** [comment]
I merged Diana's stitched notebook in the main branch. Close this pull request to avoid confusion.

**Pull request closed without merging**
